# Generated by Django 5.0.14 on 2025-12-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_result_id", models.BigIntegerField(db_index=True)),
                ("website_search_id", models.BigIntegerField()),
                ("url", models.TextField()),
                ("title", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=3, max_digits=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="searchresult",
            constraint=models.UniqueConstraint(
                fields=("search_result_id", "website_search_id"),
                name="unique_search_website",
            ),
        ),
    ]
