# Generated by Django 5.2.8 on 2025-12-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='search_keyword',
            field=models.CharField(default='product name', max_length=100),
            preserve_default=False,
        ),
    ]
