# Generated by Django 5.2.8 on 2025-12-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='searchresult',
            name='search_sear_search__b2ae11_idx',
        ),
    ]
